### ISSUE TITLE
How do you install on a raspberry pi?

### ISSUE THREAD

**Issue by mattfox27** [nullpainter/sanchez#102]
How do you install on a raspberry pi?  I did not see it in the wiki?

**Comment by nullpainter** [comment]
Use the ARM build - I note that in the final sentence of the README at https://github.com/nullpainter/sanchez

**Comment by mattfox27** [comment]
I understand that, but is it just download and unzip and thats it?

**Comment by nullpainter** [comment]
If I've done my job right, yep! I haven't tested it on a Raspberry Pi for a few years, but it should be that easy.

**Comment by creinemann** [comment]
Matt(s)... I have an instructional for the PI and satdump on my site at https://usradioguy.com/receiving-goes-hrit-with-satdump/

**Comment by creinemann** [comment]
Also, I should point out that the developers of satdump drastically changed the file output of imagery relating to geo sats. Thge new naming convention does not 'currently' work with Sanchez. 

So instead of having a file folder with today's date, and all the day/night imagery under it, it creates a file folder by time and date, with just that times output under it. See my example for goes 18.  the Json will need to be updated to handle that, as well as for pulling multiple files:
