### ISSUE TITLE
GK-2A Mask

### ISSUE THREAD

**Issue by sam210723** [nullpainter/sanchez#3]
Thought I'd send you the mask I use for GK-2A images. It's made from an IR105 image which has been clipped to 0 and 255, so it lines up perfectly with the real images. I've also included sample images for testing IR enhancement stacking.

[images.zip](https://github.com/nullpainter/sanchez/files/4970833/images.zip)

**Comment by nullpainter** [comment]
Hi Sam,

Thanks so much for this I've added your images to the repository so they can act as samples. I hope this is okay.

Does this output look like what you expect? Your image was particularly useful as it identified that my mask for GK-2A wasn't quite right. I've improved it but it's still not _entirely_ right.

I'll create a release once I'm happy with the underlay.

![overlayed](https://user-images.githubusercontent.com/1732347/88385435-6c45ed80-ce02-11ea-91bc-8a6944b0f737.jpg)

**Comment by sam210723** [comment]
That looks great! I did notice the underlay wasn't perfectly aligned, I know exactly how difficult that can be. I've tried something similar ages ago with coastal outlines and never got them quite perfect.

No problem with the images being in the repo. I can make some more if you need a bigger sample size.

**Comment by nullpainter** [comment]
Released in v0.1.0 - please give it a test!

**Comment by sam210723** [comment]
Looks good! Would you be able to add an option to apply the mask after the overlay? Sometimes the enhancement edges can be noisy like in this image.
![output](https://user-images.githubusercontent.com/5117093/88637946-263ca280-d0fe-11ea-86f7-bf21fac94331.jpg)


I've also got [this night lights underlay](https://vksdr.com/downloads/night-underlay.jpg) which you may get some interesting results with.

**Comment by nullpainter** [comment]
Sure, I love adding command-line options! I will have a play.

I had been thinking about the night light underlay. I _may_ not include it in the distribution, but it'd be a perfect candidate for the [sample images](https://github.com/nullpainter/sanchez/wiki/Sample-images) page. Although now I'm wondering if a separate underlay repository would make more sense...

**Comment by nullpainter** [comment]
Applying the night light underlay looks a bit weird as the clouds are quite bright with the blending mode I'm using for composing the IR. 

Could be considered over-engineering but I'm wondering whether building support for JSON-based profile files could be handy. This way, we could specify the stacking order (as per your request), tint, opacity, blending modes, etc. This would then be an 'advanced' feature, with command line options for either ad-hoc runs or standard processing. 

This could also be useful to define a favourite tint/contrast/brightness per satellite rather than have to type it on the command-line or shove it in a shell script.

What do you think? The alternative approach for the stacking order would be yet another command-line argument, but it's already getting _relatively_ long.

**Comment by nullpainter** [comment]
If I'm looking at the right place, the noise is only present in my mask. With your mask it looks fine. Given that I just made mine by sight, this isn't hugely surprising.

I may take yours and use it to make mine a bit better.

**Comment by sam210723** [comment]
I wouldn't be too worried about the number of command line arguments. Take a look at things like ``ffmpeg`` or ``vlc`` and see the ludicrous amount they have! The JSON profiles might be overkill right now but would make more sense if the number of args grows in the future.

Also, nice high-res underlays!

**Comment by nullpainter** [comment]
This may be all a moot point. The reason for my mask in the first place was because I wasn't properly correcting the projection of the underlay images and was instead hacking it in Photoshop and needed to hide my sins.

I've now worked out the proper way of doing it and will be updating the high-res underlays shortly.

Anyhow, I think I may always apply the mask after the overlay.

**Comment by nullpainter** [comment]
Now correctly projection-mapped! I'm including a 2200px and 4000px underlay. If the second one is used (the image below), the other images are upscaled. I figured it would come down to personal taste.

Still needs a little better alignment, but at least we're not dealing with that _and_ projection issues at the same time.

![GK2-o](https://user-images.githubusercontent.com/1732347/89094942-2bab2d00-d41d-11ea-9fd0-b4b8aeb1cfc4.jpg)

**Comment by nullpainter** [comment]
Added in v0.2.0.
