### ISSUE TITLE
GOES-16 image using a day/night underlay created by xplanet

### ISSUE THREAD

**Issue by mlavespere** [nullpainter/sanchez#51]
GOES-16 image using xplanet to generate a day/night underlay. Just replace earth.jpg and night.jpg in /usr/share/xplanet/images with the day and night files that come with Sanchez and run 

xplanet -body earth -projection rectangular -num_times 1 -geometry 10848x5424 -output underlay.jpg

![GOES16_FD_CH13_20201018T120018Z](https://user-images.githubusercontent.com/16197311/96374138-e99da780-113e-11eb-9e0f-349480c1819a.jpg)

**Comment by creinemann** [comment]
Hmm. I tried this, and replaced earth. jpg and night.jpg with the ones from the Sanchez resource folder
`xplanet -body earth -projection rectangular -num_times 1 -geometry 10848x5424  -output underlay.jpg`
But it did not generate the day/night composite, but rather a day view with just a darker area for the "night"
https://imgur.com/a/y9Fn3g1

**Comment by creinemann** [comment]
I found the error, I hade to specify the night.jpg in the default config for Xplanet
'[earth]
"Earth"
color={28, 82, 110}
night_map=night.jpg`

**Comment by nullpainter** [comment]
Thanks for sending this through, @mlavespere, and thanks for your hint about the night image, @creinemann.

I've included a note about the Xplanet config on the [Underlays](https://github.com/nullpainter/sanchez/wiki/Underlays) wiki. In order to dogfood, I created my own day/night Xplanet underlay using the images you provided, and have included this on the [sample images](https://github.com/nullpainter/sanchez/wiki/Sample-images) page.
