### ISSUE TITLE
Incorrect images being used in stitch

### ISSUE THREAD

**Issue by ZL1LAC** [nullpainter/sanchez#63]
cmd used:
`./batch.sh 2021-01-02T11:50:20`

`/root/sanchez/Sanchez reproject -s /root/images -o /root/sanchez/out/stitched.jpg -T $1 -a`

![stitched](https://user-images.githubusercontent.com/909007/103459192-32462380-4d72-11eb-8cfe-7bb6a50e1a82.jpg)
[sanchez-20210102.txt](https://github.com/nullpainter/sanchez/files/5760346/sanchez-20210102.txt)

**Comment by creinemann** [comment]
Looking at your files such as 20210101T230000Z_20210101230001-pac48per_latestBW.gif that your pulling from the handler in the satellite.json file, which uses a suffix (1-3) and (4-9)  for Electro: is being interpreted by Sanchez as an Electro file. I would change from using the root directory, and/or not have Sanchez scan the files containing the gif imagery.

**Comment by nullpainter** [comment]
Thanks @creinemann - that was my suspicion as well. There are several alternatives here:

1. We make the regex tighter in the `Satellites.json` file so the GIF imagery isn't picked up; and/or
2. @ZL1LAC removes entries from the `Satellites.json` file which aren't being used

I think the first option needs to be done in any case, but the second approach has the added benefit of speeding up directory processing (see #62 - since moving to a regex-based approach to better support Electro, initial directory processing time has taken a hit, and becomes slower with each supported satellite)

**Comment by nullpainter** [comment]
Fixed in v1.0.15.
