### ISSUE TITLE
0.5km resolution support

### ISSUE THREAD

**Issue by ZbychuButItWasTaken** [nullpainter/sanchez#64]
I think that with EWS-G1 decoded, Sanchez should support full resolution data from it (20000x18956px on channel 1) which corresponds to about .5km at nadir (0.54 to be exact). IGFOV of the sat is 1km, so the pixels do overlap, but decoder produces 20k x 20k anyway. Using the 1km mode significantly impacts the quality
I'd require a bigger underlay too, to make colored images.

**Comment by creinemann** [comment]
You could pull these images for your underlay which at best resolution is 500-meter spatial resolution.

**Comment by nullpainter** [comment]
Thanks Carl - the Blue Marble images are the source of the currently-bundled underlays.

**Comment by nullpainter** [comment]
Added as part of [v1.0.16](https://github.com/nullpainter/sanchez/releases/tag/v1.0.16). Note that for stitching, this can result in Sanchez becoming very memory hungry - for a 36,915px by 19,606px image, Sanchez was peaking at around 20Gb of RAM (!)

For the highest quality output, be sure to use an underlay which is at least 21,696px high. The blue marble images @creinemann linked to above are suitable, however they've been chunked into 21,600px square images. 

If somebody has the energy and computing grunt to stitch these together, I'll add the underlay to the sister [Sanchez underlay](https://github.com/nullpainter/sanchez-underlays) repository (otherwise I'll just do it myself). 

In the meantime, you can use any of Carl's 1km underlays in that repository, or the `Resources\world.200412.3x21600x10800.jpg` file bundled with Sanchez.
