### ISSUE TITLE
reproject issues

### ISSUE THREAD

**Issue by hasaranga** [nullpainter/sanchez#99]
Hi,
I live in southern part of Sri Lanka. Today evening, the entire sky is filled with clouds. But when I take an image from satdump(GK-2A LRIT) and send it to sanchez, there were no clouds shown over my country. It seems reproject option has an issue with countries in the edge. The cloud shown by the arrow in the image is really over my country. But the reproject option moved that cloud to left.

![output](https://github.com/nullpainter/sanchez/assets/3483400/b886e599-9646-467e-b76b-5396326f0bd4)

![out](https://github.com/nullpainter/sanchez/assets/3483400/6e3f9a42-7569-4577-bf3b-51086b1298dc)

![IMG_FD_075_IR105_20240113_124006](https://github.com/nullpainter/sanchez/assets/3483400/111d32ef-096d-4a97-b074-4f986a6fd3b9)

**Comment by creinemann** [comment]
![layered](https://github.com/nullpainter/sanchez/assets/47005123/ace7070a-e860-4e6f-a4ee-f9720217a45a)
If you layer the original HRIT Imggery rebroadcast from GK2A the cloud you are referring is in the correct position for the time it was scanned by GK2A, sent to ground ops for processing, and relayed backed to GK2A for rebroadcast. What you receive on any HRIT or LRIT geo satellite is not Live, but delayed because of processing and rebroadcast. ( and timestamped for the time of reception)
For live Imagery you would need a much bigger system for level L0 or L1 imagery.

**Comment by hasaranga** [comment]
How to get the original timestamp of given image?
